# Generated by Django 5.0.dev20230505072651 on 2023-05-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_memory_favourite_alter_images_nameimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='memorycreator',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
